/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ltp2.view;

import br.com.ltp2.model.Cliente;
import br.com.ltp2.util.ConnectionFactory;
import br.com.ltp2.util.Util;
import java.awt.List;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.collections.map.HashedMap;

/**
 *
 * @author Luiz
 */
public class NewPesquisaView extends javax.swing.JFrame {

    /**
     * Creates new form NewPesquisaView
     */
    //private String nomeCliente;
    private DefaultTableModel model;
    TableRowSorter sorter;
    private ResultSet rs;
    private Connection conn = null;
    private String path; //Caminho base
    private String pathToReportPackage; // Caminho para o package onde estão armazenados os 
    private String paramSQL;
    
    public NewPesquisaView() {
        this.conn = ConnectionFactory.getConexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInfo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbNome = new javax.swing.JRadioButton();
        rbCPF = new javax.swing.JRadioButton();
        rbTelefone = new javax.swing.JRadioButton();
        rbSexo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnBusca = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInfoKeyTyped(evt);
            }
        });

        jLabel1.setText("Buscar Por:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parâmetro de Busca:"));

        rbNome.setText("Nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        rbCPF.setText("CPF");
        rbCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCPFActionPerformed(evt);
            }
        });

        rbTelefone.setText("TEL.");
        rbTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTelefoneActionPerformed(evt);
            }
        });

        rbSexo.setText("Sexo");
        rbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbNome)
                        .addGap(18, 18, 18)
                        .addComponent(rbSexo))
                    .addComponent(rbCPF)
                    .addComponent(rbTelefone))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNome)
                    .addComponent(rbSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTelefone))
        );

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Sexo", "CPF", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tabelaClientes);

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnPrint.setText("Imprimir...");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrint)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txtInfo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnBusca)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBusca)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrint)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        try {                   
               // String sql = "";
                String val = txtInfo.getText();
                 if (rbNome.isSelected()){
                        paramSQL = "cli_nome LIKE '" + val +"%'";
                        geraBusca();
                 }else if (rbCPF.isSelected()){
                         paramSQL = "cli_cpf LIKE '" + val +"%'";
                          geraBusca();
                 }else if (rbTelefone.isSelected()){
                          paramSQL = "cli_fone LIKE '" + val +"%'";
                          geraBusca();
                 }else if (rbSexo.isSelected()){
                          paramSQL = "cli_sexo LIKE '" + val +"%'";
                          geraBusca();
                 } else
                          JOptionPane.showMessageDialog(null, "Algum tipo de parâmetro precisa ser selecionado!");

         } catch (SQLException ex) {
                 Logger.getLogger(NewPesquisaView.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void txtInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInfoKeyTyped
//        try {       
//              String sql = "";
//                String val = txtInfo.getText();
//                 if (rbNome.isSelected()){
//                     sql = "cli_nome LIKE '%" + val +"%'";
//                        geraBusca(sql);
//                 }else if (rbCPF.isSelected()){
//                          sql = "cli_cpf LIKE '%" + val +"%'";
//                          geraBusca(sql);
//                 }else if (rbTelefone.isSelected()){
//                          sql = "cli_fone LIKE '%" + val +"%'";
//                          geraBusca(sql);
//                 }else
//                          JOptionPane.showMessageDialog(null, "Algum tipo de parâmetro precisa ser selecionado!");
//                 } catch (SQLException ex) {
//                 Logger.getLogger(NewPesquisaView.class.getName()).log(Level.SEVERE, null, ex);
//         }
    }//GEN-LAST:event_txtInfoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ConnectionFactory.closeConnection(this.conn);
        } catch (SQLException ex) {
            Logger.getLogger(NewPesquisaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
            
        try {
            //try {
            gerarRelatorio();
            //JRResultSetDataSource jrRS;
            //jrRS = new JRResultSetDataSource(rs);
            //this.path = this.getClass().getClassLoader().getResource("").getPath();
            //this.pathToReportPackage = this.path + "MyReports/";
            
            //Map parametros = new HashMap();
            //JasperReport report = JasperCompileManager.compileReport("src/MyReports/clientes.jasper");
            //JasperReport report = JasperCompileManager.compileReport("E:\\IFGOIANO==============\\2019\\ProjetosJava\\AplicacaoClientes\\src\\MyReports\\clientes.jasper");
            
            //JasperPrint print = JasperFillManager​.fillReport("E:/IFGOIANO==============/2019/ProjetosJava/AplicacaoClientes/src/MyReports/clientes.jasper", null, jrRS);
            //JasperPrint print = JasperFillManager​.fillReport("E:\\IFGOIANO==============\\2019\\ProjetosJava\\AplicacaoClientes\\src\\MyReports\\clientes.jasper", null, conn);
            //JasperViewer.viewReport(print, false);
            //jv.setVisible(true);
            //} catch (JRException ex) {
              //  Logger.getLogger(NewPesquisaView.class.getName()).log(Level.SEVERE, null, ex);
            //}        
       } catch (SQLException ex) {
           Logger.getLogger(NewPesquisaView.class.getName()).log(Level.SEVERE, null, ex);
       } catch (JRException ex) {
           Logger.getLogger(NewPesquisaView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        rbCPF.setSelected(false);
        rbTelefone.setSelected(false);
        rbSexo.setSelected(false);
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCPFActionPerformed
        rbNome.setSelected(false);
        rbTelefone.setSelected(false);
        rbSexo.setSelected(false);
    }//GEN-LAST:event_rbCPFActionPerformed

    private void rbTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTelefoneActionPerformed
        rbNome.setSelected(false);
        rbCPF.setSelected(false);
        rbSexo.setSelected(false);
    }//GEN-LAST:event_rbTelefoneActionPerformed

    private void rbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSexoActionPerformed
        rbNome.setSelected(false);
        rbCPF.setSelected(false);
        rbTelefone.setSelected(false);
    }//GEN-LAST:event_rbSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPesquisaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPesquisaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCPF;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbSexo;
    private javax.swing.JRadioButton rbTelefone;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField txtInfo;
    // End of variables declaration//GEN-END:variables

private void geraBusca() throws SQLException{
   
    String sql = "select cli_cod, cli_nome,cli_sexo, cli_cpf, cli_fone from cliente where " + this.paramSQL;
        
 try {
       
       PreparedStatement ps = this.conn.prepareStatement(sql);
       this.rs = ps.executeQuery();

       //Configurando os tamanhos das colunas e instanciando a tabela
       tabelaClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
       tabelaClientes.getColumnModel().getColumn(1).setPreferredWidth(200);
       tabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(50);
       tabelaClientes.getColumnModel().getColumn(3).setPreferredWidth(110);
       tabelaClientes.getColumnModel().getColumn(4).setPreferredWidth(70);

       model = (DefaultTableModel)tabelaClientes.getModel();
       model.setNumRows(0);   
            while (this.rs.next()) {
                Integer rsCodigo = this.rs.getInt("cli_cod");
                String rsNome = this.rs.getString("cli_nome");
                String rsSexo = this.rs.getString("cli_sexo");
                String rsCpf = this.rs.getString("cli_cpf");
                String rsFone = this.rs.getString("cli_fone");
                
                //preenche os dados do banco na tabela 
                model.addRow(new Object[]{rsCodigo, rsNome,rsSexo, rsCpf, rsFone});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela " + ex);
            ex.printStackTrace();
        }finally{
           
     }
  }

    private void gerarRelatorio() throws SQLException, JRException {
        
        String sql = "select cli_cod, cli_nome, cli_sexo, cli_cpf, cli_fone from cliente where " + this.paramSQL; //cli_nome like '" + txtInfo.getText() + "%'";
        PreparedStatement ps = this.conn.prepareStatement(sql);
        ResultSet r = ps.executeQuery();
        
        JRResultSetDataSource jrRS;
        jrRS = new JRResultSetDataSource(r);
        JasperPrint print = null;
        HashMap map = new HashMap();
        File arquivo = new File("E:\\IFGOIANO==============\\2019\\ProjetosJava\\AplicacaoClientes\\src\\MyReports\\costumers.jasper");
        JasperReport report = (JasperReport) JRLoader.loadObject(arquivo);
        print = JasperFillManager​.fillReport(report,map,jrRS);
        JasperViewer.viewReport(print, false);


    }

}
